[package]
name = "nrf-monotonic"
version = "0.1.3"
authors = ["Fabio Pungg <fabiopungg@gmail.com>"]


categories = ["concurrency", "embedded", "no-std"]
description = "RTIC Monotonic implementation based on nrf timers"
# documentation = "https://docs.rs/dwt-systick-monotonic"
# repository = "https://github.com/rtic-rs/dwt-systick-monotonic"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "nrf_monotonic"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.3"
rtic-monotonic = "0.1.0-rc.2"
fugit = "0.3.0"

[dependencies.defmt]
version = "0.2.3"
optional = true

[dependencies.nrf52810-hal]
version = "0.14.0"
optional = true

[dependencies.nrf52811-hal]
version = "0.14.0"
optional = true

[dependencies.nrf52832-hal]
version = "0.14.0"
optional = true

[dependencies.nrf52833-hal]
version = "0.14.0"
optional = true

[dependencies.nrf52840-hal]
version = "0.14.0"
optional = true


[features]
default = ["52840"]

52810 = ["nrf52810-hal"]
52811 = ["nrf52811-hal"]
52832 = ["nrf52832-hal"]
52833 = ["nrf52833-hal"]
52840 = ["nrf52840-hal"]

defmt-impl = ["defmt"]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
